
package xx;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "Service01", targetNamespace = "http://com/")
public interface Service01 {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "hr", targetNamespace = "http://com/", className = "xx.Hr")
	@ResponseWrapper(localName = "hrResponse", targetNamespace = "http://com/", className = "xx.HrResponse")
	public String hr(@WebParam(name = "arg0", targetNamespace = "") String arg0);

}
